import { useState } from "react";
import AppLayout from "@/components/AppLayout";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { FileText, HardHat, Loader2, PackageCheck, Upload, X } from "lucide-react";
import { toast } from "sonner";

const api=(trpc as any).epiEpc;
function date(value:any){return value?new Date(value).toLocaleDateString("pt-BR"):"-"}

export default function MyEpiEpc(){
  const q=api.myDeliveries.useQuery();
  const [selected,setSelected]=useState<any|null>(null);
  const upload=api.uploadMySignedReceipt.useMutation({onSuccess:()=>{toast.success("Recibo enviado para comprovação.");q.refetch();setSelected(null)},onError:(e:any)=>toast.error(e.message)});
  function submitFile(delivery:any,file:File){if(!["application/pdf","image/png","image/jpeg"].includes(file.type))return toast.error("Envie PDF, PNG ou JPG.");const reader=new FileReader();reader.onload=()=>upload.mutate({id:Number(delivery.id),fileBase64:String(reader.result),fileName:file.name,mimeType:file.type,signedAt:new Date().toISOString()});reader.readAsDataURL(file)}
  const rows=q.data??[];
  return <AppLayout><div className="max-w-6xl mx-auto p-6 space-y-5"><header><h1 className="text-2xl font-bold flex items-center gap-2 text-primary"><HardHat size={23}/>Meu EPI/EPC</h1><p className="text-sm text-muted-foreground mt-1">Equipamentos recebidos, recibos, comprovantes e histórico sob sua responsabilidade.</p></header>
    <div className="grid sm:grid-cols-3 gap-3"><Metric label="Entregas registradas" value={rows.length}/><Metric label="Sob responsabilidade" value={rows.filter((x:any)=>!['devolvido','substituido'].includes(x.status)).length}/><Metric label="Pendências de comprovante" value={rows.filter((x:any)=>!['assinado','comprovado'].includes(x.signature_status)).length}/></div>
    <div className="border rounded-md bg-white overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50"><tr><th className="p-3 text-left">Equipamento</th><th className="p-3 text-left">Entrega</th><th className="p-3 text-left">CA/Lote</th><th className="p-3 text-left">Próxima troca</th><th className="p-3 text-left">Situação</th><th className="p-3"></th></tr></thead><tbody>{rows.map((r:any)=><tr key={r.id} className="border-t"><td className="p-3"><b>{r.asset_description}</b><div className="text-xs text-muted-foreground">{r.manufacturer||""} {r.model||""} · {r.quantity} unidade(s)</div></td><td className="p-3">{date(r.delivery_date)}</td><td className="p-3">{r.ca_number||"-"}<div className="text-xs text-muted-foreground">Lote {r.lot||"-"}</div></td><td className="p-3">{r.replacement_periodicity||r.replacement_criteria||"Conforme avaliação técnica"}</td><td className="p-3">{['assinado','comprovado'].includes(r.signature_status)?<span className="text-emerald-700 font-semibold">Comprovado</span>:<span className="text-amber-700 font-semibold">Assinatura pendente</span>}</td><td className="p-3"><Button size="sm" variant="outline" onClick={()=>setSelected(r)}><FileText size={14}/>Recibo e documentos</Button></td></tr>)}</tbody></table>{!rows.length&&<div className="p-12 text-center text-muted-foreground"><PackageCheck size={30} className="mx-auto mb-2"/>Nenhuma entrega vinculada ao seu cadastro.</div>}</div>
    {selected&&(
      <Documents delivery={selected} onClose={()=>setSelected(null)} onFile={(f:File)=>submitFile(selected,f)} uploading={upload.isPending}/>
    )}
  </div></AppLayout>
}

function Metric({label,value}:{label:string,value:any}){return <div className="border bg-white rounded-md p-4"><div className="text-xs text-muted-foreground">{label}</div><div className="text-2xl font-bold text-primary mt-2">{value}</div></div>}
function Documents({delivery,onClose,onFile,uploading}:{delivery:any,onClose:any,onFile:any,uploading:boolean}){const q=api.myDeliveryDocuments.useQuery({id:Number(delivery.id)});return <div className="fixed inset-0 z-50 bg-black/45 flex items-center justify-center p-4" onClick={onClose}><div className="bg-white rounded-md shadow-xl w-full max-w-2xl p-5" onClick={e=>e.stopPropagation()}><div className="flex justify-between"><div><h2 className="font-bold">Recibo e documentos</h2><p className="text-xs text-muted-foreground">{delivery.asset_description} · entrega em {date(delivery.delivery_date)}</p></div><Button size="icon" variant="ghost" onClick={onClose}><X size={18}/></Button></div><div className="mt-4 divide-y border rounded-md">{(q.data??[]).map((d:any)=><div key={d.id} className="p-3 flex justify-between"><div><b className="text-sm">{d.title}</b><div className="text-xs text-muted-foreground">{d.document_type} · versão {d.document_version||1}</div></div>{d.file_url&&<a href={d.file_url} target="_blank" rel="noreferrer" className="text-sm text-primary">Abrir</a>}</div>)}{!q.data?.length&&<div className="p-5 text-center text-sm text-muted-foreground">O recibo ainda não foi disponibilizado.</div>}</div>{!['assinado','comprovado'].includes(delivery.signature_status)&&<label className="mt-4 w-full border-2 border-dashed rounded-md p-5 flex flex-col items-center cursor-pointer hover:bg-slate-50"><Upload size={22} className="text-primary"/><b className="text-sm mt-2">Anexar recibo assinado</b><span className="text-xs text-muted-foreground">PDF, PNG ou JPG de até 15 MB</span><input type="file" accept="application/pdf,image/png,image/jpeg" className="hidden" disabled={uploading} onChange={e=>{const f=e.target.files?.[0];if(f)onFile(f)}}/>{uploading&&<Loader2 size={16} className="animate-spin mt-2"/>}</label>}</div></div>}
