import AppLayout from "@/components/AppLayout";
import { trpc } from "@/lib/trpc";
import { BookOpen, Building2, Check, Clock, Library, Search } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";

export default function WhiteLabelCourseLibrary() {
  const library = (trpc.whiteLabelNetwork as any).listCourseLibrary.useQuery();
  const [search, setSearch] = useState("");
  const [editing, setEditing] = useState<any>(null);
  const save = (trpc.whiteLabelNetwork as any).saveCourseLibrary.useMutation({
    onSuccess: () => { toast.success("Biblioteca e distribuição atualizadas."); setEditing(null); library.refetch(); },
    onError: (error:any) => toast.error(error.message || "Não foi possível atualizar a biblioteca."),
  });
  const courses = useMemo(() => (library.data?.courses || []).filter((course:any) => `${course.title} ${course.description || ""} ${course.template_category || ""} ${course.profession || ""}`.toLowerCase().includes(search.toLowerCase())), [library.data?.courses, search]);
  const open = (course:any) => setEditing({ moduleId:Number(course.id), selected:!!course.selected, customTitle:course.display_title || course.title, sortOrder:Number(course.sort_order || 0), companyIds:course.companyIds || [] });
  return <AppLayout><div className="p-4 md:p-6 space-y-5">
    <header><h1 className="text-2xl font-bold text-primary flex items-center gap-2"><Library size={24}/> Biblioteca de Cursos da Rede</h1><p className="text-sm text-muted-foreground mt-1">Selecione conteúdos oficiais do SuperAdmin e distribua somente aos clientes autorizados.</p></header>
    <section className="border-l-4 border-cyan-600 bg-cyan-50 p-4 text-sm text-cyan-950"><b>Produção central, distribuição pela rede.</b> O Estúdio estrutural é administrado pelo SuperAdmin. Aqui a White Label escolhe, organiza e entrega cursos publicados aos seus clientes.</section>
    <div className="grid md:grid-cols-3 gap-3"><div className="border bg-white p-4"><div className="text-xs text-muted-foreground">Cursos oficiais</div><div className="text-2xl font-bold">{library.data?.courses?.length || 0}</div></div><div className="border bg-white p-4"><div className="text-xs text-muted-foreground">Na biblioteca da rede</div><div className="text-2xl font-bold text-emerald-700">{(library.data?.courses || []).filter((c:any)=>c.selected).length}</div></div><div className="border bg-white p-4"><div className="text-xs text-muted-foreground">Clientes da rede</div><div className="text-2xl font-bold">{library.data?.companies?.length || 0}</div></div></div>
    <label className="relative block max-w-lg"><Search size={16} className="absolute left-3 top-3 text-muted-foreground"/><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Pesquisar curso, tema, categoria ou profissão" className="h-10 w-full rounded-md border bg-white pl-9 pr-3"/></label>
    <div className="grid md:grid-cols-2 xl:grid-cols-3 gap-4">{courses.map((course:any) => <article key={course.id} className="border bg-white overflow-hidden"><div className="aspect-[16/7] bg-slate-100">{course.image_url ? <img src={course.image_url} alt="" className="h-full w-full object-cover"/> : <div className="h-full flex items-center justify-center"><BookOpen size={32} className="text-slate-300"/></div>}</div><div className="p-4"><div className="flex items-start gap-3"><div className="flex-1"><h2 className="font-semibold">{course.display_title || course.title}</h2><p className="text-sm text-muted-foreground line-clamp-2 mt-1">{course.description || "Curso oficial da plataforma."}</p></div>{course.selected && <span className="inline-flex items-center gap-1 text-xs font-semibold text-emerald-700"><Check size={14}/> Selecionado</span>}</div><div className="mt-3 flex flex-wrap gap-3 text-xs text-muted-foreground"><span className="inline-flex items-center gap-1"><Clock size={13}/>{course.durationMinutes || 0} min</span><span>{course.template_category || "Corporativo"}</span><span>{course.companyIds?.length || 0} cliente(s)</span></div><button onClick={() => open(course)} className="mt-4 w-full rounded-md border px-3 py-2 text-sm hover:bg-slate-50">Configurar distribuição</button></div></article>)}</div>
    {!library.isLoading && !courses.length && <div className="border border-dashed p-10 text-center text-muted-foreground">Nenhum curso oficial encontrado.</div>}
    {editing && <div className="fixed inset-0 z-50 bg-black/40 flex items-center justify-center p-4" onClick={() => setEditing(null)}><section className="w-full max-w-xl bg-white p-5" onClick={e => e.stopPropagation()}><div className="flex justify-between gap-3"><div><h2 className="text-lg font-bold">Distribuição do curso</h2><p className="text-sm text-muted-foreground">Apenas clientes marcados receberão o conteúdo.</p></div><button onClick={() => setEditing(null)} className="px-3 py-2 border rounded-md">Fechar</button></div><div className="mt-5 space-y-4"><label className="flex items-center gap-3 border p-3"><input type="checkbox" checked={editing.selected} onChange={e => setEditing({...editing,selected:e.target.checked})}/><span><b>Disponível na biblioteca da rede</b><span className="block text-xs text-muted-foreground">Desmarcar desativa a distribuição sem apagar histórico.</span></span></label><label className="text-sm block">Título comercial na rede<input value={editing.customTitle} onChange={e => setEditing({...editing,customTitle:e.target.value})} className="mt-1 h-10 w-full border rounded-md px-3"/></label><label className="text-sm block">Ordem<input type="number" min={0} value={editing.sortOrder} onChange={e => setEditing({...editing,sortOrder:Number(e.target.value)})} className="mt-1 h-10 w-full border rounded-md px-3"/></label><div><div className="text-sm mb-2 flex items-center gap-2"><Building2 size={15}/> Clientes autorizados</div><div className="max-h-64 overflow-y-auto border divide-y">{(library.data?.companies || []).map((company:any) => <label key={company.id} className="flex items-center gap-3 p-3"><input type="checkbox" disabled={!editing.selected} checked={editing.companyIds.includes(Number(company.id))} onChange={e => setEditing({...editing,companyIds:e.target.checked ? [...editing.companyIds,Number(company.id)] : editing.companyIds.filter((id:number)=>id !== Number(company.id))})}/><span><b className="text-sm">{company.name}</b><span className="block text-xs text-muted-foreground">{company.cnpj || "CNPJ não informado"}</span></span></label>)}</div></div></div><div className="mt-5 flex justify-end gap-2"><button onClick={() => setEditing(null)} className="px-4 py-2 border rounded-md">Cancelar</button><button disabled={save.isPending} onClick={() => save.mutate(editing)} className="px-4 py-2 bg-primary text-white rounded-md">Salvar distribuição</button></div></section></div>}
  </div></AppLayout>;
}
