export type CommercialFeatureContent = {
  headline: string;
  benefits: string[];
  flow: string[];
  integrations: string[];
  result: string;
  pillarCode: string;
  audience: string[];
};

const content = (
  headline: string,
  pillarCode: string,
  benefits: string[],
  flow: string[],
  integrations: string[],
  result: string,
  audience: string[],
): CommercialFeatureContent => ({ headline, pillarCode, benefits, flow, integrations, result, audience });

// Conteúdo comercial oficial das funcionalidades anteriores ao manifesto vivo.
// O código é a chave estável: nomes e textos podem evoluir sem quebrar snapshots.
export const LEGACY_COMMERCIAL_FEATURE_CONTENT: Record<string, CommercialFeatureContent> = {
  gro_pgr_dinamico: content("Riscos mudam. Seu PGR acompanha.", "safety_engineering", ["Inventário vivo por GSE", "Cálculo estruturado de criticidade", "Revisões sem perda do histórico"], ["GSE", "Perigo", "Avaliação", "Controle", "Revisão"], ["GSE/GHE", "PCMSO", "Planos de Ação"], "A organização trabalha com uma visão atual dos riscos e preserva cada decisão técnica.", ["SESMT", "Engenharia"]),
  suite_laudos_tecnicos: content("Laudos técnicos conectados à realidade da operação.", "safety_engineering", ["Modelos técnicos padronizados", "Assinatura e versionamento", "Dados reaproveitados do inventário de riscos"], ["Dados", "Avaliação", "Laudo", "Assinatura", "Arquivo"], ["PGR", "GSE/GHE", "PPP"], "LTCAT, insalubridade e periculosidade deixam de ser documentos isolados.", ["SESMT", "Engenharia"]),
  ecossistema_nr06: content("Cada entrega de EPI vira uma evidência verificável.", "sesmt_intelligence", ["CA, estoque e validade no mesmo fluxo", "Recibo individual por colaborador", "Biometria opcional para ciência"], ["Equipamento", "Entrega", "Ciência", "Controle", "Auditoria"], ["Colaboradores", "GSE/GHE", "Biometria"], "A empresa reduz papel e comprova quem recebeu, quando recebeu e qual item foi entregue.", ["SESMT", "RH"]),
  ciclo_asos_360: content("Enxergue a conformidade antes que ela vire pendência.", "sesmt_intelligence", ["Obrigações consolidadas", "Pendências clicáveis", "Prioridade por criticidade e prazo"], ["Obrigação", "Pendência", "Responsável", "Ação", "Conclusão"], ["PCMSO", "ASO", "Treinamentos"], "O SESMT sabe exatamente onde agir e acompanha a regularização até o fim.", ["SESMT", "Diretoria"]),
  anamnese_epidemiologica: content("Transforme dados de saúde em prevenção organizada.", "annual_health_report", ["Previstos versus realizados", "Leitura de faltas e alterações", "Indicadores de afastamento e absenteísmo"], ["Dados", "Indicador", "Análise", "Prioridade", "Acompanhamento"], ["PCMSO", "Exames", "Afastamentos"], "A saúde ocupacional passa a orientar ações com base em evidências do próprio negócio.", ["Médico", "SESMT", "Diretoria"]),
  prontuario_blindado: content("Conecte o SST ao ERP sem redigitar a operação.", "integrations", ["Integração controlada por API", "Menos retrabalho cadastral", "Rastreabilidade das sincronizações"], ["Sistema de origem", "API", "Validação", "Plataforma", "Retorno"], ["TOTVS", "RH", "Webhooks"], "As informações circulam com segurança entre os sistemas corporativos.", ["TI", "Administrador"]),
  gest_o_atas_corporativas: content("Decisão tomada. Responsável definido. Evidência preservada.", "governance", ["Atas estruturadas", "Assinaturas e anexos", "Planos de ação vinculados"], ["Reunião", "Decisão", "Responsável", "Evidência", "PDF"], ["CIPA", "Planos de Ação", "Documentos"], "Cada reunião produz um registro acionável e pronto para auditoria.", ["RH", "SESMT", "Governança"]),
  "789654": content("Documentos entram. Dados utilizáveis saem.", "technology", ["Leitura assistida por OCR", "Conferência antes da gravação", "Documento original preservado"], ["Upload", "Leitura", "Conferência", "Vínculo", "Histórico"], ["Exames", "Certificados", "Dossiê"], "A digitação manual diminui sem abrir mão da validação humana.", ["RH", "SESMT", "Clínica"]),
  "456": content("eSocial de SST com validação, retorno e rastreabilidade.", "esocial", ["Eventos S-2210, S-2220 e S-2240", "Críticas claras antes do envio", "Protocolos e reenvios registrados"], ["Evento", "Validação", "Envio", "Retorno", "Correção"], ["CAT", "ASO", "PGR"], "A empresa acompanha o ciclo do evento sem depender de controles paralelos.", ["SESMT", "Administrador"]),
  centro_de_intelig_ncia_sesmt___painel_360_: content("Toda a operação de SST em uma única leitura.", "sesmt_intelligence", ["Indicadores de saúde e segurança", "Filtros por estrutura organizacional", "Acesso direto à origem da informação"], ["Dados", "Painel 360°", "Drill-down", "Ação", "Evidência"], ["PGR", "PCMSO", "eSocial"], "O SESMT deixa de procurar dados em telas separadas e passa a conduzir a operação.", ["SESMT", "Diretoria"]),
  indicadores_de_riscos_ocupacionais: content("Descubra onde os riscos realmente se concentram.", "sesmt_intelligence", ["Riscos por filial e setor", "Comparação entre GSEs", "Visão integrada de exposições"], ["PGR", "Classificação", "Agrupamento", "Indicador", "Prioridade"], ["PGR", "GSE/GHE", "Ergonomia"], "A priorização deixa de ser intuitiva e passa a refletir a exposição registrada.", ["SESMT", "Engenharia"]),
  monitoramento_de_pend_ncias: content("Nenhuma pendência importante fica invisível.", "sesmt_intelligence", ["Criticidade e prazo", "Responsável identificado", "Acompanhamento até a conclusão"], ["Detecção", "Classificação", "Responsável", "Cobrança", "Conclusão"], ["Conformidade", "Planos de Ação", "Notificações"], "A equipe concentra energia no que exige providência agora.", ["SESMT", "Gestor"]),
  gest_o_de_planos_de_a__o: content("Não deixe uma pendência virar um problema.", "sesmt_intelligence", ["Responsáveis claramente definidos", "Controle de prazo", "Evidências e indicadores de conclusão"], ["Problema", "Ação", "Responsável", "Prazo", "Evidência", "Conclusão"], ["PGR", "CIPA", "Auditorias"], "Cada desvio ganha um plano, um dono e uma comprovação de encerramento.", ["SESMT", "Gestor", "Diretoria"]),
  drill_down_inteligente: content("Do indicador executivo ao registro que explica o número.", "business_intelligence", ["Navegação em profundidade", "Filtros preservados", "Origem do dado acessível"], ["Indicador", "Empresa", "Filial", "Setor", "Registro"], ["Dashboards", "Visão 360°", "Auditoria"], "A análise termina em uma causa verificável, não em um gráfico sem contexto.", ["Diretoria", "SESMT"]),
  vis_o_por_empresa__filial_e_setor: content("Compare unidades e encontre onde agir primeiro.", "business_intelligence", ["Filtros organizacionais", "Leitura entre períodos", "Comparação de desempenho"], ["Empresa", "Filial", "Setor", "Cargo", "Período"], ["Dashboards", "Colaboradores", "Indicadores"], "A gestão identifica diferenças relevantes entre operações e direciona recursos com precisão.", ["Diretoria", "Gestor", "SESMT"]),
  mapa_de_criticidade: content("Prioridade visível para decisões mais rápidas.", "business_intelligence", ["Pontos críticos destacados", "Leitura por severidade", "Acesso à pendência de origem"], ["Dados", "Criticidade", "Mapa", "Prioridade", "Ação"], ["Riscos", "Pendências", "Planos de Ação"], "Os temas mais urgentes aparecem antes que se percam em listas extensas.", ["Diretoria", "SESMT"]),
  indicadores_comparativos: content("Veja evolução, recorrência e diferença entre unidades.", "business_intelligence", ["Séries históricas", "Comparação entre filiais", "Leitura de melhora ou piora"], ["Período", "Indicador", "Comparação", "Tendência", "Decisão"], ["Dashboards", "Visão 360°", "Relatórios"], "A empresa acompanha se as ações estão realmente mudando o cenário.", ["Diretoria", "SESMT"]),
  gest_o_orientada_por_evid_ncias: content("Cada indicador sustentado pela evidência que o compõe.", "business_intelligence", ["Relação entre número e registro", "Documentos acessíveis", "Trilha pronta para auditoria"], ["Indicador", "Registro", "Documento", "Evidência", "Decisão"], ["Auditoria", "Documentos", "Planos de Ação"], "A tomada de decisão ganha contexto e capacidade de comprovação.", ["Diretoria", "Auditoria", "SESMT"]),
  vis_o_360____intelig_ncia_integrada: content("Uma visão única para uma operação que antes estava fragmentada.", "business_intelligence", ["Dados de vários módulos", "Jornada ocupacional conectada", "Indicadores com contexto"], ["Pessoas", "Saúde", "Segurança", "Conformidade", "Decisão"], ["Dossiê", "PGR", "PCMSO"], "Gestores enxergam relações que sistemas separados não conseguem mostrar.", ["Diretoria", "RH", "SESMT"]),
  analytics_preditivo: content("Antecipe tendências antes que virem recorrência.", "business_intelligence", ["Leitura de padrões históricos", "Sinais de concentração", "Apoio à prevenção baseada em dados"], ["Histórico", "Padrão", "Tendência", "Alerta", "Prevenção"], ["Visão 360°", "Indicadores", "Planos de Ação"], "A operação passa a agir sobre sinais, não apenas sobre fatos já consumados.", ["Diretoria", "SESMT"]),
  dashboards_executivos: content("A situação do SST entendida em poucos minutos.", "business_intelligence", ["Indicadores estratégicos", "Filtros por unidade e período", "Leitura rápida para liderança"], ["Dados", "Indicadores", "Dashboard", "Análise", "Decisão"], ["Visão 360°", "Relatórios", "Conformidade"], "A diretoria acompanha desempenho e risco sem navegar pela operação técnica.", ["Diretoria", "Gestor"]),
  motor_de_comunica__o_inteligente: content("A mensagem certa chega ao público certo.", "engagement", ["Segmentação organizacional", "Campanhas multicanal", "Histórico de comunicação"], ["Mensagem", "Público", "Canal", "Envio", "Acompanhamento"], ["Colaboradores", "E-mail", "WhatsApp"], "Comunicações deixam de ser genéricas e passam a acompanhar cada jornada.", ["RH", "SESMT", "Comunicação"]),
  drps: content("Meça riscos psicossociais sem romper o anonimato.", "integrated_intelligence", ["Participação anônima", "Indicadores por grupo", "Base para plano de ação"], ["Ciclo", "Participação", "Análise", "Matriz", "Ação"], ["NR-01", "AEP", "PGR"], "A empresa compreende fatores psicossociais preservando a confiança dos participantes.", ["RH", "SESMT", "Psicólogo"]),
  gestao_vacinacao_corp: content("Segurança do trabalho acompanhada por indicadores acionáveis.", "sesmt_intelligence", ["Acidentes e incidentes consolidados", "Entregas e treinamentos monitorados", "Ações preventivas acompanhadas"], ["Ocorrência", "Indicador", "Análise", "Ação", "Resultado"], ["CAT", "EPI/EPC", "Treinamentos"], "A prevenção ganha uma leitura integrada do que acontece no trabalho.", ["SESMT", "Diretoria"]),
  aep: content("Entenda a atividade real antes de definir a intervenção.", "integrated_intelligence", ["Avaliação por função e setor", "Rastreabilidade técnica", "Integração com riscos e ações"], ["Atividade", "Observação", "Avaliação", "Risco", "Ação"], ["NR-17", "PGR", "Planos de Ação"], "A ergonomia passa a refletir o trabalho observado e suas necessidades concretas.", ["SESMT", "Ergonomia"]),
  laudo_aep_ergonomia: content("Ergonomia documentada, priorizada e conectada ao plano de ação.", "safety_engineering", ["Diagnóstico conforme NR-17", "Riscos organizados por atividade", "Medidas acompanhadas até a conclusão"], ["Atividade", "Avaliação", "Diagnóstico", "Plano", "Evidência"], ["AEP", "PGR", "Planos de Ação"], "O laudo deixa de encerrar a análise e passa a iniciar a melhoria.", ["SESMT", "Engenharia"]),
  campaigns: content("Comunique saúde e prevenção sem perder o público no caminho.", "engagement", ["Segmentação de destinatários", "Conteúdo reutilizável", "Registro de envio"], ["Campanha", "Público", "Conteúdo", "Envio", "Métrica"], ["Colaboradores", "E-mail", "Calendário"], "A comunicação corporativa fica organizada e ligada às ações da plataforma.", ["RH", "SESMT", "Comunicação"]),
  "12345": content("Suporte que aprende com a própria plataforma.", "technology", ["Respostas imediatas", "Artigos por perfil", "Conteúdo atualizado com o produto"], ["Dúvida", "Busca", "Artigo", "Orientação", "Próxima ação"], ["Manual", "IA", "Perfis"], "Usuários encontram orientação dentro do fluxo e reduzem dependência do atendimento humano.", ["Todos os perfis"]),
  whatsapp: content("Leve alertas operacionais para o canal que as pessoas acompanham.", "engagement", ["Mensagens vinculadas a processos", "Segmentação por público", "Histórico de disparos"], ["Evento", "Mensagem", "Destinatário", "Envio", "Registro"], ["Campanhas", "Requisições", "Treinamentos"], "Prazos e documentos importantes chegam ao colaborador com mais agilidade.", ["RH", "SESMT", "Colaborador"]),
  profiles: content("Cada profissional vê o que precisa e somente o que pode acessar.", "strategic_differentials", ["Experiências por responsabilidade", "Dados clínicos segregados", "Permissões por empresa e perfil"], ["Usuário", "Perfil", "Permissão", "Experiência", "Auditoria"], ["RH", "SESMT", "Central Médica"], "A plataforma combina produtividade com controle rigoroso de acesso.", ["Diretoria", "Administrador"]),
  dashboard_dos_ciclos: content("Do cenário psicossocial ao ponto que exige ação.", "integrated_intelligence", ["Ciclos consolidados", "Drill-down por estrutura", "Fatores críticos destacados"], ["Ciclo", "Resultado", "Filial", "Setor", "Ação"], ["DRPS", "AEP", "Plano de Ação"], "O SESMT entende onde os fatores se concentram sem expor respostas individuais.", ["SESMT", "RH", "Psicólogo"]),
  corporate_minutes: content("Reuniões que terminam com decisões executáveis.", "governance", ["Pauta e participantes", "Assinaturas e fotos", "Ações com responsáveis e prazo"], ["Pauta", "Reunião", "Decisão", "Assinatura", "Plano"], ["CIPA", "Documentos", "Planos de Ação"], "A ata se torna uma evidência viva da governança corporativa.", ["RH", "SESMT", "CIPA"]),
  parametriza__o_dos_gse: content("Cadastre o grupo uma vez e conecte toda a jornada ocupacional.", "safety_engineering", ["Estrutura única de exposição", "Vínculos atuais e históricos", "Reutilização em PGR e PCMSO"], ["Filial", "Setor", "Cargo", "GSE", "Riscos"], ["Colaboradores", "PGR", "PCMSO"], "O GSE vira a matriz que conecta pessoas, riscos, exames e histórico.", ["SESMT", "Médico"]),
  ethics_channel: content("Escuta protegida com tratamento responsável e rastreável.", "governance", ["Relato seguro", "Controle de acesso", "Acompanhamento e evidências"], ["Relato", "Triagem", "Apuração", "Providência", "Conclusão"], ["Governança", "Atas", "Planos de Ação"], "A organização estrutura o tratamento das denúncias sem expor indevidamente o denunciante.", ["RH", "Compliance", "Diretoria"]),
  an_lise_de_risco_psicossocial: content("Converta escuta e avaliação em um plano preventivo NR-01.", "integrated_intelligence", ["DRPS quantitativo e AEP qualitativa", "Matriz de risco integrada", "Cronograma preventivo"], ["DRPS", "AEP", "Matriz", "Plano", "PGR"], ["NR-01", "PGR", "Indicadores"], "A análise psicossocial gera uma trilha técnica da identificação à prevenção.", ["SESMT", "RH", "Psicólogo"]),
  dossi__mestre_do_colaborador___single_view: content("A jornada ocupacional completa, sem procurar documento por documento.", "business_intelligence", ["Visão individual consolidada", "Histórico cronológico", "Documentos integrados sem duplicidade"], ["Cadastro", "Vínculos", "Saúde", "Segurança", "Histórico"], ["Dossiê", "Central Médica", "Treinamentos"], "Cada colaborador passa a ter uma linha do tempo confiável e acessível conforme a permissão.", ["RH", "SESMT", "Médico"]),
  smart_import___people_analytics: content("Traga o passado para dentro da análise atual.", "business_intelligence", ["Importação estruturada", "Validação antes da gravação", "Histórico enriquecido"], ["Arquivo", "Mapeamento", "Validação", "Importação", "Analytics"], ["Colaboradores", "Histórico Laboral", "BI"], "Empresas novas na plataforma não precisam começar seus indicadores do zero.", ["RH", "Diretoria"]),
  pgr: content("Do inventário de riscos ao plano de prevenção em um único documento vivo.", "safety_engineering", ["Riscos por GSE", "Revisões versionadas", "Anexos e evidências incorporados"], ["GSE", "Risco", "Avaliação", "Plano", "PDF"], ["GSE/GHE", "PCMSO", "Planos de Ação"], "O PGR conecta a análise técnica à execução e preserva toda a evolução documental.", ["SESMT", "Engenharia"]),
  pcmso: content("Riscos ocupacionais transformados em monitoramento médico.", "occupational_health", ["Importação do PGR vigente", "Exames definidos por risco e GSE", "Documento médico versionado"], ["PGR", "Risco", "Decisão médica", "Exame", "PCMSO"], ["Central Médica", "Exames", "ASO"], "O médico trabalha sobre a exposição real e o SESMT recebe uma base operacional para os exames.", ["Médico", "SESMT"]),
  medical_center: content("Cuidado ocupacional com contexto, histórico e sigilo.", "occupational_health", ["Prontuário restrito", "Atendimentos e encaminhamentos", "Linha do tempo clínica ocupacional"], ["Colaborador", "Atendimento", "Conduta", "Documento", "Histórico"], ["PCMSO", "Exames", "Dossiê"], "A equipe médica acompanha o trabalhador sem misturar informação clínica com gestão administrativa.", ["Médico"]),
  exam_requests: content("O exame certo para a pessoa certa, no momento certo.", "occupational_health", ["Necessidade definida pelo PCMSO", "Conferência por exercício", "Repetição justificada sem duplicidade"], ["PCMSO", "Funcionário", "Histórico", "Requisição", "Resultado"], ["GSE/GHE", "Clínicas", "Portal do Colaborador"], "As requisições passam a considerar risco, histórico e situação individual.", ["SESMT", "Médico"]),
  cat: content("Transforme o relato do acidente em uma CAT conferida e rastreável.", "esocial", ["Tabelas oficiais pesquisáveis", "Sugestões assistidas por IA", "Conferência antes do S-2210"], ["Relato", "Códigos", "Conferência", "CAT", "S-2210"], ["eSocial", "Colaboradores", "Central Médica"], "O preenchimento técnico fica mais claro sem transferir a decisão para a IA.", ["SESMT", "Médico"]),
  ppp: content("O histórico laboral construído durante todo o vínculo.", "esocial", ["Linha do tempo de funções e exposições", "Importação de dados anteriores", "Consolidação contínua para o PPP"], ["Admissão", "GSE", "Riscos", "Mudanças", "PPP"], ["PGR", "LTCAT", "Exames"], "O PPP deixa de ser reconstruído no desligamento e passa a nascer da operação diária.", ["SESMT", "RH"]),
  vaccination: content("Campanhas, doses e comprovantes organizados por colaborador.", "occupational_health", ["Cadastro de vacinas e parceiros", "Alertas de próxima dose", "Comprovante no prontuário"], ["Campanha", "Aplicação", "Dose", "Alerta", "Comprovante"], ["Central Médica", "Dossiê", "Portal do Colaborador"], "A empresa acompanha a imunização e o colaborador acessa seu próprio histórico.", ["Médico", "RH", "Colaborador"]),
  compliance: content("Transforme obrigações em uma fila clara de providências.", "governance", ["Indicadores clicáveis", "Responsável e prazo", "Documento comprobatório vinculado"], ["Obrigação", "Status", "Pendência", "Ação", "Evidência"], ["PGR", "PCMSO", "eSocial"], "Conformidade deixa de ser uma fotografia e passa a orientar o próximo passo.", ["SESMT", "RH", "Diretoria"]),
  epi_epc: content("Controle o ciclo do equipamento, não apenas a entrega.", "sesmt_intelligence", ["Catálogo com CA e validade", "Entrega individual rastreável", "Estoque e pendências"], ["Cadastro", "Estoque", "Entrega", "Ciência", "Reposição"], ["GSE/GHE", "Dossiê", "Biometria"], "A empresa comprova proteção fornecida e acompanha necessidades de reposição.", ["SESMT", "Colaborador"]),
  occupational_leave: content("Atestados e afastamentos sem perder prazo, documento ou histórico.", "occupational_health", ["Recebimento e validação", "Controle de período e retorno", "Indicadores de absenteísmo"], ["Documento", "Validação", "Afastamento", "Retorno", "Indicador"], ["Dossiê", "Central Médica", "eSocial"], "RH e saúde ocupacional acompanham cada ocorrência com responsabilidades separadas.", ["RH", "Médico", "SESMT"]),
  first_aid: content("Kits prontos quando a emergência não pode esperar.", "sesmt_intelligence", ["Itens e validade por local", "Inspeções registradas", "Pendências de reposição"], ["Kit", "Inventário", "Inspeção", "Alerta", "Reposição"], ["Filiais", "Treinamentos", "Conformidade"], "Cada unidade sabe o que possui, o que venceu e o que precisa repor.", ["SESMT", "Gestor"]),
  cipa: content("Todo o processo da CIPA com protocolo e memória institucional.", "cipa_sipat", ["Eleição e mandato", "Atas e reuniões", "Protocolos e relatórios detalhados"], ["Edital", "Eleição", "Mandato", "Reunião", "Relatório"], ["Atas", "SIPAT", "Treinamentos"], "A empresa preserva o processo eleitoral e as evidências de atuação da comissão.", ["CIPA", "SESMT", "RH"]),
  sipat: content("Planeje, comunique e comprove cada etapa da SIPAT.", "cipa_sipat", ["Programação centralizada", "Conteúdos e participantes", "Evidências e relatório final"], ["Planejamento", "Agenda", "Comunicação", "Participação", "Relatório"], ["CIPA", "Cursos", "Campanhas"], "A semana interna vira um projeto rastreável, não uma coleção de arquivos soltos.", ["CIPA", "SESMT", "RH"]),
  dds: content("DDS online com presença, ciência e protocolo.", "cipa_sipat", ["Conteúdo por equipe", "Aceite individual", "Relatório de participação"], ["Tema", "Público", "DDS", "Ciência", "Protocolo"], ["Colaboradores", "Treinamentos", "Dossiê"], "O diálogo diário ganha alcance digital e comprovação por participante.", ["SESMT", "Gestor", "Colaborador"]),
  courses: content("Conhecimento disponível para quem precisa aprender e comprovar.", "learning", ["Biblioteca organizada", "Trilhas de aprendizagem", "Progresso individual"], ["Curso", "Matrícula", "Aprendizagem", "Avaliação", "Conclusão"], ["Treinamentos Obrigatórios", "Certificados", "Dossiê"], "A capacitação corporativa fica acessível, mensurável e conectada ao histórico do colaborador.", ["RH", "Treinamento", "Colaborador"]),
  certificates: content("Concluiu, comprovou, encontrou quando precisou.", "learning", ["Emissão automática", "Validação do documento", "Armazenamento individual"], ["Conclusão", "Emissão", "Validação", "Dossiê", "Reciclagem"], ["Cursos", "Dossiê", "Treinamentos Obrigatórios"], "Certificados deixam de circular por e-mail e passam a compor a trajetória de capacitação.", ["RH", "Treinamento", "Colaborador"]),
  preventive: content("Prevenção contínua além das campanhas pontuais.", "learning", ["Conteúdo educativo organizado", "Campanhas temáticas", "Acesso recorrente pelo colaborador"], ["Tema", "Conteúdo", "Campanha", "Participação", "Acompanhamento"], ["Biblioteca", "Campanhas", "Central Médica"], "A saúde preventiva se mantém presente durante todo o ano.", ["RH", "Médico", "Colaborador"]),
  ai_studio: content("Crie conteúdo estruturado sem começar de uma página em branco.", "technology", ["Apoio de IA à produção", "Estrutura editável", "Publicação em cursos e pesquisas"], ["Objetivo", "Rascunho IA", "Revisão", "Publicação", "Uso"], ["Cursos", "Pesquisas", "Manual"], "A equipe acelera a produção e mantém a validação humana antes de publicar.", ["Treinamento", "Administrador"]),
  ai: content("IA para acelerar o trabalho, sem substituir a decisão profissional.", "technology", ["Sugestões contextualizadas", "Validação humana obrigatória", "Rastreabilidade interna de uso"], ["Contexto", "Sugestão", "Revisão", "Decisão", "Registro"], ["PGR", "PCMSO", "CAT"], "Profissionais ganham velocidade mantendo autoria e responsabilidade técnica.", ["Todos os perfis técnicos"]),
  ocr: content("Leia documentos em escala e confira antes de registrar.", "technology", ["Extração assistida", "Processamento em lote", "Vínculo individual seguro"], ["Arquivo", "OCR", "Conferência", "Identificação", "Registro"], ["Exames", "Certificados", "Dossiê"], "Grandes volumes entram na plataforma com menos digitação e mais controle.", ["RH", "SESMT", "Clínica"]),
  survey_editor: content("Crie avaliações que acompanham a realidade da sua organização.", "technology", ["Questionários configuráveis", "Tipos de resposta variados", "Publicação por público"], ["Perguntas", "Lógica", "Público", "Aplicação", "Resultado"], ["Pesquisas", "Campanhas", "Análises"], "A empresa estrutura coletas próprias sem depender de desenvolvimento para cada formulário.", ["RH", "Administrador"]),
  integrations: content("Faça a plataforma conversar com o ecossistema da empresa.", "integrations", ["APIs e webhooks", "Validação de dados", "Monitoramento de sincronizações"], ["Origem", "Integração", "Validação", "Destino", "Retorno"], ["ERP", "RH", "eSocial"], "Dados fluem entre sistemas com menos retrabalho e maior rastreabilidade.", ["TI", "Administrador"]),
  reports: content("Dados operacionais convertidos em leitura gerencial.", "reports", ["Dashboards interativos", "Relatórios em PDF", "Exportação estruturada"], ["Dados", "Filtro", "Indicador", "Relatório", "Decisão"], ["Visão 360°", "Análise Personalizada", "Auditoria"], "Cada área acessa a visão adequada para acompanhar resultado e comprovar execução.", ["Diretoria", "RH", "SESMT"]),
};

