import { TRPCError } from "@trpc/server";
import { sql as drzSql } from "drizzle-orm";
import { z } from "zod";
import crypto from "crypto";
import fs from "fs";
import path from "path";
import { getDb } from "../db";
import { protectedProcedure, router } from "./trpc";

const HEALTH_ROLES = new Set(["rh", "sesmt", "admin", "company_admin", "admin_global", "super_admin"]);
const MANAGER_ROLES = new Set(["chefia", ...HEALTH_ROLES]);
let tablesReady = false;

function rowsOf(result:any):any[]{return Array.isArray(result?.[0])?result[0]:Array.isArray(result)?result:[]}
function roleOf(ctx:any){return String(ctx.user?.role||"")}
function companyOf(ctx:any){const id=Number(ctx.user?.companyId||0);if(!id)throw new TRPCError({code:"BAD_REQUEST",message:"Empresa não identificada."});return id}
function requireHealth(ctx:any){if(!HEALTH_ROLES.has(roleOf(ctx)))throw new TRPCError({code:"FORBIDDEN",message:"Acesso restrito ao RH e ao SESMT."})}
function requireManager(ctx:any){if(!MANAGER_ROLES.has(roleOf(ctx)))throw new TRPCError({code:"FORBIDDEN"})}
function dateOnly(value:any){return value?new Date(value).toISOString().slice(0,10):null}
function inclusiveDays(start:string,end:string){const a=new Date(`${start}T12:00:00Z`).getTime();const b=new Date(`${end}T12:00:00Z`).getTime();return Math.max(1,Math.floor((b-a)/86400000)+1)}
export function calculateLeaveReviewFlags(totalDays:number,startDate:string,previousEndDate?:string|null){const gap=previousEndDate?Math.floor((new Date(`${startDate}T12:00:00Z`).getTime()-new Date(`${previousEndDate}T12:00:00Z`).getTime())/86400000):null;return{benefitReviewRequired:totalDays>15,recurrenceReviewRequired:gap!==null&&gap>=0&&gap<=60}}

async function ensureTables(){
  if(tablesReady)return;const db=await getDb();if(!db)throw new TRPCError({code:"INTERNAL_SERVER_ERROR"});
  await db.execute(drzSql`CREATE TABLE IF NOT EXISTS occupational_leave_cases (
    id INT AUTO_INCREMENT PRIMARY KEY, company_id INT NOT NULL, collaborator_id INT NOT NULL,
    document_type VARCHAR(60) NOT NULL, duration_unit VARCHAR(20) NOT NULL DEFAULT 'days',
    issue_date DATE NOT NULL, start_date DATE NOT NULL, end_date DATE NOT NULL,
    start_time TIME NULL, end_time TIME NULL, total_days INT NOT NULL DEFAULT 0, total_hours DECIMAL(8,2) NOT NULL DEFAULT 0,
    issuer_name VARCHAR(255), issuer_registration VARCHAR(120), cid_code VARCHAR(30), medical_reason TEXT,
    administrative_note TEXT, status VARCHAR(40) NOT NULL DEFAULT 'pendente', review_note TEXT,
    consistency_status VARCHAR(40) NOT NULL DEFAULT 'pendente', consistency_details JSON NULL,
    benefit_review_required TINYINT(1) NOT NULL DEFAULT 0, recurrence_review_required TINYINT(1) NOT NULL DEFAULT 0,
    recurrence_case_id INT NULL, return_expected_date DATE NULL, return_actual_date DATE NULL,
    return_status VARCHAR(40) NOT NULL DEFAULT 'retorno_previsto', return_note TEXT,
    needs_occupational_review TINYINT(1) NOT NULL DEFAULT 0, validated_by INT NULL, validated_at DATETIME NULL,
    created_by INT NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_leave_company_status (company_id,status,start_date), INDEX idx_leave_user (collaborator_id,start_date),
    INDEX idx_leave_return (company_id,return_expected_date,return_status)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
  await db.execute(drzSql`CREATE TABLE IF NOT EXISTS occupational_leave_documents (
    id INT AUTO_INCREMENT PRIMARY KEY, company_id INT NOT NULL, case_id INT NOT NULL, collaborator_id INT NOT NULL,
    document_kind VARCHAR(50) NOT NULL DEFAULT 'original', file_name VARCHAR(255) NOT NULL, mime_type VARCHAR(120) NOT NULL,
    file_size INT NOT NULL, file_hash VARCHAR(64) NOT NULL, private_path VARCHAR(1024) NOT NULL,
    document_version INT NOT NULL DEFAULT 1, uploaded_by INT NOT NULL, uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_leave_doc_case (case_id,document_kind,document_version), INDEX idx_leave_doc_hash (company_id,file_hash)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
  await db.execute(drzSql`CREATE TABLE IF NOT EXISTS occupational_leave_events (
    id INT AUTO_INCREMENT PRIMARY KEY, company_id INT NOT NULL, case_id INT NOT NULL,
    event_type VARCHAR(60) NOT NULL, previous_status VARCHAR(40), new_status VARCHAR(40),
    public_note TEXT, private_note TEXT, user_id INT NOT NULL, user_name VARCHAR(255), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_leave_event_case (case_id,created_at), INDEX idx_leave_event_company (company_id,created_at)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
  await db.execute(drzSql`CREATE TABLE IF NOT EXISTS occupational_leave_alerts (
    id INT AUTO_INCREMENT PRIMARY KEY, company_id INT NOT NULL, case_id INT NOT NULL, collaborator_id INT NOT NULL,
    alert_type VARCHAR(60) NOT NULL, severity VARCHAR(20) NOT NULL DEFAULT 'warning', title VARCHAR(255) NOT NULL,
    message TEXT NOT NULL, status VARCHAR(30) NOT NULL DEFAULT 'aberto', resolved_by INT NULL, resolved_at DATETIME NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY uq_leave_alert (case_id,alert_type),
    INDEX idx_leave_alert_company (company_id,status,created_at)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
  tablesReady=true;
}

async function logEvent(db:any,cid:number,caseId:number,type:string,user:any,oldStatus?:string|null,newStatus?:string|null,publicNote?:string|null,privateNote?:string|null){
  await db.execute(drzSql`INSERT INTO occupational_leave_events (company_id,case_id,event_type,previous_status,new_status,public_note,private_note,user_id,user_name) VALUES (${cid},${caseId},${type},${oldStatus||null},${newStatus||null},${publicNote||null},${privateNote||null},${user.id},${user.name||user.email||null})`);
}

async function createAlert(db:any,cid:number,caseId:number,userId:number,type:string,title:string,message:string,severity="warning"){
  await db.execute(drzSql`INSERT INTO occupational_leave_alerts (company_id,case_id,collaborator_id,alert_type,severity,title,message) VALUES (${cid},${caseId},${userId},${type},${severity},${title},${message}) ON DUPLICATE KEY UPDATE title=VALUES(title),message=VALUES(message),severity=VALUES(severity),status=IF(status='resolvido','resolvido','aberto')`);
}

async function createInternalNotification(db:any,userId:number,cid:number,title:string,body:string,link:string,key:string,priority="normal"){
  try{await db.execute(drzSql`INSERT INTO notifications (user_id,company_id,type,priority,title,body,link,icon,dedup_key) VALUES (${userId},${cid},'saude_ocupacional',${priority},${title},${body},${link},'stethoscope',${key}) ON DUPLICATE KEY UPDATE body=VALUES(body),read_at=NULL,created_at=NOW()`)}catch{}
}

function privateRoot(){return process.env.PRIVATE_UPLOAD_DIR|| (process.env.NODE_ENV==="production"?"/var/www/saudedotrabalho/private_uploads":path.join(process.cwd(),"private_uploads"))}
function decodeDocument(fileBase64:string,mimeType:string){if(!["application/pdf","image/png","image/jpeg"].includes(mimeType))throw new TRPCError({code:"BAD_REQUEST",message:"Envie PDF, PNG ou JPG."});const raw=fileBase64.replace(/^data:[^;]+;base64,/,"");const buf=Buffer.from(raw,"base64");if(!buf.length||buf.length>15*1024*1024)throw new TRPCError({code:"BAD_REQUEST",message:"O documento deve possuir até 15 MB."});return buf}

async function storePrivateDocument(db:any,cid:number,caseId:number,userId:number,file:{fileBase64:string,fileName:string,mimeType:string},kind="original"){
  const buffer=decodeDocument(file.fileBase64,file.mimeType);const hash=crypto.createHash("sha256").update(buffer).digest("hex");
  const dup:any=await db.execute(drzSql`SELECT id,case_id FROM occupational_leave_documents WHERE company_id=${cid} AND file_hash=${hash} LIMIT 1`);
  const ext=file.mimeType==="application/pdf"?"pdf":file.mimeType==="image/png"?"png":"jpg";const dir=path.join(privateRoot(),"occupational_health",String(cid),String(caseId));fs.mkdirSync(dir,{recursive:true});const storedName=`${kind}_${Date.now()}_${crypto.randomBytes(4).toString("hex")}.${ext}`;const privatePath=path.join(dir,storedName);fs.writeFileSync(privatePath,buffer);
  const v:any=await db.execute(drzSql`SELECT COALESCE(MAX(document_version),0)+1 AS v FROM occupational_leave_documents WHERE case_id=${caseId} AND document_kind=${kind}`);const version=Number(rowsOf(v)[0]?.v||1);
  await db.execute(drzSql`INSERT INTO occupational_leave_documents (company_id,case_id,collaborator_id,document_kind,file_name,mime_type,file_size,file_hash,private_path,document_version,uploaded_by) VALUES (${cid},${caseId},${userId},${kind},${file.fileName},${file.mimeType},${buffer.length},${hash},${privatePath},${version},${userId})`);
  return{duplicateCaseId:rowsOf(dup)[0]?.case_id?Number(rowsOf(dup)[0].case_id):null,hash,version};
}

async function refreshReturnAlerts(db:any,cid:number){
  const r:any=await db.execute(drzSql`SELECT id,collaborator_id,return_expected_date,return_status FROM occupational_leave_cases WHERE company_id=${cid} AND status IN ('validado','validado_com_ressalva') AND return_expected_date IS NOT NULL AND return_status NOT IN ('retornou','retorno_concluido','afastamento_prorrogado') AND return_expected_date<=DATE_ADD(CURDATE(),INTERVAL 3 DAY)`);
  for(const c of rowsOf(r)){const late=new Date(c.return_expected_date)<new Date(new Date().toISOString().slice(0,10));await createAlert(db,cid,Number(c.id),Number(c.collaborator_id),late?"retorno_pendente":"retorno_proximo",late?"Retorno pendente":"Retorno ao trabalho próximo",late?"O retorno previsto ainda não foi confirmado.":`Retorno previsto para ${dateOnly(c.return_expected_date)}.`,late?"high":"warning")}
}

function occupationalReportHtml(company:any,rows:any[],includeCid:boolean){
  const esc=(value:any)=>String(value??"").replace(/[<>&"]/g,char=>({"<":"&lt;",">":"&gt;","&":"&amp;","\"":"&quot;"}[char] as string));
  const totalDays=rows.reduce((sum,row)=>sum+Number(row.total_days||0),0);const totalHours=rows.reduce((sum,row)=>sum+Number(row.total_hours||0),0);
  const body=rows.map(row=>`<tr><td>${esc(row.name)}</td><td>${esc(row.branch||"-")}</td><td>${esc(row.sector||"-")}</td><td>${esc(row.document_type)}</td><td>${esc(dateOnly(row.start_date))} a ${esc(dateOnly(row.end_date))}</td><td>${Number(row.total_days||0)} d / ${Number(row.total_hours||0)} h</td><td>${esc(row.status)}</td><td>${esc(dateOnly(row.return_expected_date)||"-")}</td>${includeCid?`<td>${esc(row.cid_code||"Não informado")}</td>`:""}</tr>`).join("");
  return `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><style>@page{size:A4 landscape;margin:14mm}body{font-family:Arial,sans-serif;color:#172033;font-size:10px}h1{color:#0e2c46;font-size:22px;margin:0}.meta{color:#64748b;margin:6px 0 18px}.summary{display:flex;gap:10px;margin:0 0 16px}.card{border:1px solid #cbd5e1;padding:10px;min-width:120px}.card b{display:block;font-size:18px;color:#0e2c46;margin-top:4px}table{width:100%;border-collapse:collapse}th{background:#0e2c46;color:white;padding:7px;text-align:left}td{padding:6px;border-bottom:1px solid #dbe3ec;vertical-align:top}.note{margin-top:16px;color:#64748b;border-top:1px solid #cbd5e1;padding-top:8px}</style></head><body><h1>Relatório de Atestados e Afastamentos</h1><div class="meta">${esc(company?.name)} · CNPJ ${esc(company?.cnpj||"-")} · Gerado em ${new Date().toLocaleString("pt-BR")}</div><div class="summary"><div class="card">Registros<b>${rows.length}</b></div><div class="card">Dias perdidos<b>${totalDays}</b></div><div class="card">Horas perdidas<b>${totalHours}</b></div></div><table><thead><tr><th>Colaborador</th><th>Filial</th><th>Setor</th><th>Tipo</th><th>Período</th><th>Duração</th><th>Status</th><th>Retorno</th>${includeCid?"<th>CID</th>":""}</tr></thead><tbody>${body||`<tr><td colspan="${includeCid?9:8}">Nenhum registro encontrado.</td></tr>`}</tbody></table><div class="note">Documento administrativo gerado pela plataforma. Alertas previdenciários indicam necessidade de análise humana e não representam decisão automática. ${includeCid?"Este relatório contém dado pessoal sensível e deve ser acessado somente por pessoas autorizadas.":"Informações clínicas sensíveis não foram incluídas."}</div></body></html>`;
}

const createInput=z.object({
  documentType:z.enum(["atestado","declaracao","afastamento","outro"]),durationUnit:z.enum(["days","hours"]),issueDate:z.string(),startDate:z.string(),endDate:z.string(),startTime:z.string().optional(),endTime:z.string().optional(),totalDays:z.number().int().min(0).optional(),totalHours:z.number().min(0).optional(),issuerName:z.string().max(255).optional(),issuerRegistration:z.string().max(120).optional(),cidCode:z.string().max(30).optional(),medicalReason:z.string().max(5000).optional(),administrativeNote:z.string().max(5000).optional(),fileBase64:z.string().min(20),fileName:z.string().min(1).max(255),mimeType:z.string(),
});

export const occupationalHealthRouter=router({
  create:protectedProcedure.input(createInput).mutation(async({ctx,input})=>{
    await ensureTables();const cid=companyOf(ctx);const db=await getDb();if(!db)throw new TRPCError({code:"INTERNAL_SERVER_ERROR"});
    const start=dateOnly(input.startDate)!;const end=dateOnly(input.endDate)!;if(new Date(end)<new Date(start))throw new TRPCError({code:"BAD_REQUEST",message:"A data final não pode ser anterior à inicial."});
    const totalDays=input.durationUnit==="days"?Math.max(1,input.totalDays||inclusiveDays(start,end)):0;const totalHours=input.durationUnit==="hours"?Number(input.totalHours||0):0;
    const issues:string[]=[];if(!input.issuerName)issues.push("Profissional emitente não informado");if(!input.issuerRegistration)issues.push("Registro profissional não informado");if(input.durationUnit==="hours"&&totalHours<=0)issues.push("Quantidade de horas não informada");
    const prior:any=await db.execute(drzSql`SELECT id,end_date,cid_code FROM occupational_leave_cases WHERE company_id=${cid} AND collaborator_id=${ctx.user.id} AND start_date<=${start} AND DATEDIFF(${start},end_date) BETWEEN 0 AND 60 ORDER BY end_date DESC LIMIT 1`);const priorCase=rowsOf(prior)[0];const flags=calculateLeaveReviewFlags(totalDays,start,dateOnly(priorCase?.end_date));const recurrence=flags.recurrenceReviewRequired;const benefit=flags.benefitReviewRequired;
    const ins:any=await db.execute(drzSql`INSERT INTO occupational_leave_cases (company_id,collaborator_id,document_type,duration_unit,issue_date,start_date,end_date,start_time,end_time,total_days,total_hours,issuer_name,issuer_registration,cid_code,medical_reason,administrative_note,status,consistency_status,consistency_details,benefit_review_required,recurrence_review_required,recurrence_case_id,return_expected_date,created_by) VALUES (${cid},${ctx.user.id},${input.documentType},${input.durationUnit},${input.issueDate},${start},${end},${input.startTime||null},${input.endTime||null},${totalDays},${totalHours},${input.issuerName||null},${input.issuerRegistration||null},${input.cidCode||null},${input.medicalReason||null},${input.administrativeNote||null},'pendente',${issues.length?'revisao_recomendada':'consistente'},${JSON.stringify(issues)},${benefit?1:0},${recurrence?1:0},${priorCase?.id||null},${end},${ctx.user.id})`);const caseId=Number((Array.isArray(ins)?ins[0]:ins)?.insertId||0);
    const stored=await storePrivateDocument(db,cid,caseId,Number(ctx.user.id),input);if(stored.duplicateCaseId){issues.push(`Arquivo idêntico já foi anexado no caso ${stored.duplicateCaseId}`);await db.execute(drzSql`UPDATE occupational_leave_cases SET consistency_status='revisao_recomendada',consistency_details=${JSON.stringify(issues)} WHERE id=${caseId}`)}
    await logEvent(db,cid,caseId,"documento_enviado",ctx.user,null,"pendente","Documento enviado pelo colaborador.",input.administrativeNote||null);
    if(benefit)await createAlert(db,cid,caseId,Number(ctx.user.id),"superior_15_dias","Afastamento superior a 15 dias","Avaliar necessidade de tratamento previdenciário a partir do 16º dia, conforme o caso. A plataforma não toma essa decisão automaticamente.","high");
    if(recurrence)await createAlert(db,cid,caseId,Number(ctx.user.id),"recorrencia_60_dias","Possível recorrência em 60 dias","Foi identificado novo afastamento dentro de 60 dias. Avaliar relação com o motivo anterior e eventual tratamento previdenciário.","high");
    const admins:any=await db.execute(drzSql`SELECT id FROM users WHERE company_id=${cid} AND is_active=1 AND role IN ('rh','sesmt','admin','company_admin')`);for(const u of rowsOf(admins))await createInternalNotification(db,Number(u.id),cid,"Novo atestado pendente",`${ctx.user.name||"Colaborador"} enviou um documento para análise.`,"/admin/atestados-afastamentos",`leave-${caseId}-admin-${u.id}`,"alta");
    const managers:any=await db.execute(drzSql`SELECT m.id FROM users m JOIN users e ON e.company_id=m.company_id AND e.id=${ctx.user.id} WHERE m.company_id=${cid} AND m.is_active=1 AND m.role='chefia' AND m.sector_id=e.sector_id`);for(const m of rowsOf(managers))await createInternalNotification(db,Number(m.id),cid,"Ciência de ausência",`${ctx.user.name||"Colaborador"} registrou ausência de ${start} a ${end}. Documento em análise pelo RH.`,"/admin/atestados-afastamentos",`leave-${caseId}-manager-${m.id}`);
    return{ok:true,id:caseId,consistencyStatus:issues.length?"revisao_recomendada":"consistente",benefitReviewRequired:benefit,recurrenceReviewRequired:recurrence};
  }),
  myCases:protectedProcedure.query(async({ctx})=>{await ensureTables();const cid=companyOf(ctx);const db=await getDb();if(!db)return[];const r:any=await db.execute(drzSql`SELECT id,document_type,duration_unit,issue_date,start_date,end_date,start_time,end_time,total_days,total_hours,status,consistency_status,benefit_review_required,recurrence_review_required,return_expected_date,return_actual_date,return_status,created_at FROM occupational_leave_cases WHERE company_id=${cid} AND collaborator_id=${ctx.user.id} ORDER BY start_date DESC,id DESC`);return rowsOf(r)}),
  listQueue:protectedProcedure.input(z.object({status:z.enum(["pendente","em_analise","validado","validado_com_ressalva","necessita_correcao","arquivado"]).optional(),branchId:z.number().optional(),sectorId:z.number().optional()}).optional()).query(async({ctx,input})=>{requireHealth(ctx);await ensureTables();const cid=companyOf(ctx);const db=await getDb();if(!db)return[];const where=[`c.company_id=${cid}`];if(input?.status)where.push(`c.status='${input.status}'`);if(input?.branchId)where.push(`u.branch_id=${Number(input.branchId)}`);if(input?.sectorId)where.push(`u.sector_id=${Number(input.sectorId)}`);const r:any=await db.execute(`SELECT c.*,u.name AS collaborator_name,u.cpf,u.position,b.name AS branch_name,s.name AS sector_name,v.name AS validator_name FROM occupational_leave_cases c JOIN users u ON u.id=c.collaborator_id LEFT JOIN branches b ON b.id=u.branch_id LEFT JOIN sectors s ON s.id=u.sector_id LEFT JOIN users v ON v.id=c.validated_by WHERE ${where.join(" AND ")} ORDER BY FIELD(c.status,'pendente','em_analise','necessita_correcao','validado_com_ressalva','validado','arquivado'),c.start_date DESC,c.id DESC LIMIT 1000`);return rowsOf(r)}),
  managerAbsences:protectedProcedure.query(async({ctx})=>{requireManager(ctx);await ensureTables();const cid=companyOf(ctx);const db=await getDb();if(!db)return[];const sector=Number(ctx.user.sectorId||0);const filter=roleOf(ctx)==="chefia"?`AND u.sector_id=${sector}`:"";const r:any=await db.execute(`SELECT c.id,u.name AS collaborator_name,u.position,b.name AS branch_name,s.name AS sector_name,c.document_type,c.start_date,c.end_date,c.total_days,c.total_hours,c.status,c.return_expected_date,c.return_actual_date,c.return_status FROM occupational_leave_cases c JOIN users u ON u.id=c.collaborator_id LEFT JOIN branches b ON b.id=u.branch_id LEFT JOIN sectors s ON s.id=u.sector_id WHERE c.company_id=${cid} ${filter} ORDER BY c.start_date DESC LIMIT 500`);return rowsOf(r)}),
  getCase:protectedProcedure.input(z.object({id:z.number().int()})).query(async({ctx,input})=>{requireHealth(ctx);await ensureTables();const cid=companyOf(ctx);const db=await getDb();if(!db)return null;const r:any=await db.execute(drzSql`SELECT c.*,u.name AS collaborator_name,u.cpf,u.position,b.name AS branch_name,s.name AS sector_name FROM occupational_leave_cases c JOIN users u ON u.id=c.collaborator_id LEFT JOIN branches b ON b.id=u.branch_id LEFT JOIN sectors s ON s.id=u.sector_id WHERE c.id=${input.id} AND c.company_id=${cid} LIMIT 1`);const row=rowsOf(r)[0];if(!row)throw new TRPCError({code:"NOT_FOUND"});const docs:any=await db.execute(drzSql`SELECT id,document_kind,file_name,mime_type,file_size,document_version,uploaded_at FROM occupational_leave_documents WHERE case_id=${input.id} AND company_id=${cid} ORDER BY id DESC`);const events:any=await db.execute(drzSql`SELECT e.*,u.name AS actor_name FROM occupational_leave_events e LEFT JOIN users u ON u.id=e.user_id WHERE e.case_id=${input.id} AND e.company_id=${cid} ORDER BY e.created_at DESC`);return{...row,documents:rowsOf(docs),events:rowsOf(events)}}),
  downloadDocument:protectedProcedure.input(z.object({id:z.number().int()})).query(async({ctx,input})=>{await ensureTables();const cid=companyOf(ctx);const db=await getDb();if(!db)throw new TRPCError({code:"INTERNAL_SERVER_ERROR"});const r:any=await db.execute(drzSql`SELECT d.*,c.collaborator_id FROM occupational_leave_documents d JOIN occupational_leave_cases c ON c.id=d.case_id WHERE d.id=${input.id} AND d.company_id=${cid} LIMIT 1`);const d=rowsOf(r)[0];if(!d)throw new TRPCError({code:"NOT_FOUND"});if(!HEALTH_ROLES.has(roleOf(ctx))&&Number(d.collaborator_id)!==Number(ctx.user.id))throw new TRPCError({code:"FORBIDDEN"});if(!fs.existsSync(d.private_path))throw new TRPCError({code:"NOT_FOUND",message:"Arquivo não localizado no armazenamento privado."});return{fileName:d.file_name,mimeType:d.mime_type,dataBase64:`data:${d.mime_type};base64,${fs.readFileSync(d.private_path).toString("base64")}`}}),
  review:protectedProcedure.input(z.object({id:z.number().int(),status:z.enum(["pendente","em_analise","validado","validado_com_ressalva","necessita_correcao","arquivado"]),reviewNote:z.string().max(10000).optional(),needsOccupationalReview:z.boolean().optional()})).mutation(async({ctx,input})=>{requireHealth(ctx);await ensureTables();const cid=companyOf(ctx);const db=await getDb();if(!db)throw new TRPCError({code:"INTERNAL_SERVER_ERROR"});const r:any=await db.execute(drzSql`SELECT c.*,u.name AS collaborator_name FROM occupational_leave_cases c JOIN users u ON u.id=c.collaborator_id WHERE c.id=${input.id} AND c.company_id=${cid} LIMIT 1`);const c=rowsOf(r)[0];if(!c)throw new TRPCError({code:"NOT_FOUND"});const validated=["validado","validado_com_ressalva"].includes(input.status);await db.execute(drzSql`UPDATE occupational_leave_cases SET status=${input.status},review_note=${input.reviewNote||null},needs_occupational_review=${input.needsOccupationalReview?1:0},validated_by=${validated?ctx.user.id:null},validated_at=${validated?new Date():null} WHERE id=${input.id} AND company_id=${cid}`);await logEvent(db,cid,input.id,"validacao_rh",ctx.user,c.status,input.status,validated?"Afastamento validado pelo RH.":"Situação administrativa atualizada.",input.reviewNote||null);await createInternalNotification(db,Number(c.collaborator_id),cid,"Atestado atualizado",`Seu documento referente ao período de ${dateOnly(c.start_date)} a ${dateOnly(c.end_date)} está com status: ${input.status}.`,"/meus-atestados",`leave-${input.id}-employee-${input.status}`);const managers:any=await db.execute(drzSql`SELECT m.id FROM users m JOIN users e ON e.id=${c.collaborator_id} WHERE m.company_id=${cid} AND m.is_active=1 AND m.role='chefia' AND m.sector_id=e.sector_id`);for(const m of rowsOf(managers))await createInternalNotification(db,Number(m.id),cid,"Afastamento atualizado",`O afastamento de ${c.collaborator_name}, de ${dateOnly(c.start_date)} a ${dateOnly(c.end_date)}, está com status administrativo: ${input.status}.`,"/admin/atestados-afastamentos",`leave-${input.id}-manager-${input.status}-${m.id}`);return{ok:true}}),
  updateReturn:protectedProcedure.input(z.object({id:z.number().int(),returnStatus:z.enum(["retorno_previsto","aguardando_retorno","retornou","retorno_pendente","afastamento_prorrogado","novo_afastamento","encaminhado_avaliacao","retorno_concluido"]),returnExpectedDate:z.string().optional(),returnActualDate:z.string().optional(),needsOccupationalReview:z.boolean().optional(),note:z.string().max(10000).optional()})).mutation(async({ctx,input})=>{requireHealth(ctx);await ensureTables();const cid=companyOf(ctx);const db=await getDb();if(!db)throw new TRPCError({code:"INTERNAL_SERVER_ERROR"});const r:any=await db.execute(drzSql`SELECT * FROM occupational_leave_cases WHERE id=${input.id} AND company_id=${cid}`);const c=rowsOf(r)[0];if(!c)throw new TRPCError({code:"NOT_FOUND"});await db.execute(drzSql`UPDATE occupational_leave_cases SET return_status=${input.returnStatus},return_expected_date=${input.returnExpectedDate||c.return_expected_date},return_actual_date=${input.returnActualDate||null},needs_occupational_review=${input.needsOccupationalReview?1:0},return_note=${input.note||null} WHERE id=${input.id}`);await logEvent(db,cid,input.id,"retorno_atualizado",ctx.user,c.return_status,input.returnStatus,"Fluxo de retorno ao trabalho atualizado.",input.note||null);if(["retornou","retorno_concluido","afastamento_prorrogado"].includes(input.returnStatus))await db.execute(drzSql`UPDATE occupational_leave_alerts SET status='resolvido',resolved_by=${ctx.user.id},resolved_at=NOW() WHERE case_id=${input.id} AND alert_type IN ('retorno_proximo','retorno_pendente')`);return{ok:true}}),
  alerts:protectedProcedure.query(async({ctx})=>{requireHealth(ctx);await ensureTables();const cid=companyOf(ctx);const db=await getDb();if(!db)return[];await refreshReturnAlerts(db,cid);const r:any=await db.execute(drzSql`SELECT a.*,u.name AS collaborator_name,c.start_date,c.end_date FROM occupational_leave_alerts a JOIN users u ON u.id=a.collaborator_id JOIN occupational_leave_cases c ON c.id=a.case_id WHERE a.company_id=${cid} AND a.status='aberto' ORDER BY FIELD(a.severity,'critical','high','warning'),a.created_at DESC`);return rowsOf(r)}),
  resolveAlert:protectedProcedure.input(z.object({id:z.number().int()})).mutation(async({ctx,input})=>{requireHealth(ctx);const cid=companyOf(ctx);const db=await getDb();if(!db)throw new TRPCError({code:"INTERNAL_SERVER_ERROR"});await db.execute(drzSql`UPDATE occupational_leave_alerts SET status='resolvido',resolved_by=${ctx.user.id},resolved_at=NOW() WHERE id=${input.id} AND company_id=${cid}`);return{ok:true}}),
  dashboard:protectedProcedure.query(async({ctx})=>{requireHealth(ctx);await ensureTables();const cid=companyOf(ctx);const db=await getDb();if(!db)return{};await refreshReturnAlerts(db,cid);const r:any=await db.execute(drzSql`SELECT COUNT(*) total_cases,SUM(total_days) days_lost,SUM(total_hours) hours_lost,AVG(NULLIF(total_days,0)) avg_days,SUM(recurrence_review_required) recurrent_cases,SUM(benefit_review_required) over_15_days,SUM(status IN ('pendente','em_analise','necessita_correcao')) pending_cases FROM occupational_leave_cases WHERE company_id=${cid}`);const active:any=await db.execute(drzSql`SELECT COUNT(*) c FROM users WHERE company_id=${cid} AND is_active=1 AND employment_status='active' AND role NOT IN ('super_admin','admin_global')`);const byMonth:any=await db.execute(drzSql`SELECT DATE_FORMAT(start_date,'%Y-%m') label,COUNT(*) cases,SUM(total_days) days FROM occupational_leave_cases WHERE company_id=${cid} GROUP BY label ORDER BY label DESC LIMIT 12`);const bySector:any=await db.execute(drzSql`SELECT COALESCE(s.name,'Sem setor') label,COUNT(*) cases,SUM(c.total_days) days FROM occupational_leave_cases c JOIN users u ON u.id=c.collaborator_id LEFT JOIN sectors s ON s.id=u.sector_id WHERE c.company_id=${cid} GROUP BY s.id,s.name ORDER BY days DESC LIMIT 20`);const summary=rowsOf(r)[0]||{};const employees=Number(rowsOf(active)[0]?.c||0);const periodDays=30;return{...summary,active_employees:employees,absence_rate:employees?Number(((Number(summary.days_lost||0)/(employees*periodDays))*100).toFixed(2)):0,byMonth:rowsOf(byMonth),bySector:rowsOf(bySector)}}),
  cidReport:protectedProcedure.query(async({ctx})=>{requireHealth(ctx);await ensureTables();const cid=companyOf(ctx);const db=await getDb();if(!db)return[];const r:any=await db.execute(drzSql`SELECT COALESCE(NULLIF(cid_code,''),'Não informado') cid,COUNT(*) cases,SUM(total_days) days_lost FROM occupational_leave_cases WHERE company_id=${cid} GROUP BY cid ORDER BY days_lost DESC,cases DESC LIMIT 50`);return rowsOf(r)}),
  employeeTimeline:protectedProcedure.input(z.object({collaboratorId:z.number().int()})).query(async({ctx,input})=>{requireHealth(ctx);await ensureTables();const cid=companyOf(ctx);const db=await getDb();if(!db)return[];const r:any=await db.execute(drzSql`SELECT id,document_type,issue_date,start_date,end_date,total_days,total_hours,status,benefit_review_required,recurrence_review_required,return_expected_date,return_actual_date,return_status,created_at FROM occupational_leave_cases WHERE company_id=${cid} AND collaborator_id=${input.collaboratorId} ORDER BY start_date DESC,id DESC`);return rowsOf(r)}),
  generatePdf:protectedProcedure.input(z.object({includeCid:z.boolean().default(false)})).mutation(async({ctx,input})=>{requireHealth(ctx);await ensureTables();const cid=companyOf(ctx);const db=await getDb();if(!db)throw new TRPCError({code:"INTERNAL_SERVER_ERROR"});const companyResult:any=await db.execute(drzSql`SELECT name,cnpj FROM companies WHERE id=${cid} LIMIT 1`);const reportResult:any=await db.execute(drzSql`SELECT u.name,b.name branch,s.name sector,c.document_type,c.start_date,c.end_date,c.total_days,c.total_hours,c.status,c.return_expected_date,c.cid_code FROM occupational_leave_cases c JOIN users u ON u.id=c.collaborator_id LEFT JOIN branches b ON b.id=u.branch_id LEFT JOIN sectors s ON s.id=u.sector_id WHERE c.company_id=${cid} ORDER BY c.start_date DESC,c.id DESC LIMIT 3000`);const puppeteer=(await import("puppeteer")).default;const browser=await puppeteer.launch({headless:true,executablePath:process.env.PUPPETEER_EXECUTABLE_PATH||undefined,args:["--no-sandbox","--disable-setuid-sandbox","--disable-dev-shm-usage"]});let bytes:Uint8Array;try{const page=await browser.newPage();await page.setContent(occupationalReportHtml(rowsOf(companyResult)[0],rowsOf(reportResult),input.includeCid),{waitUntil:"load"});bytes=await page.pdf({format:"A4",landscape:true,printBackground:true});}finally{await browser.close()}return{fileName:`relatorio_atestados_afastamentos_${new Date().toISOString().slice(0,10)}.pdf`,dataBase64:`data:application/pdf;base64,${Buffer.from(bytes).toString("base64")}`}}),
  exportCsv:protectedProcedure.query(async({ctx})=>{requireHealth(ctx);await ensureTables();const cid=companyOf(ctx);const db=await getDb();if(!db)return{csv:""};const r:any=await db.execute(drzSql`SELECT u.name,b.name branch,s.name sector,c.document_type,c.issue_date,c.start_date,c.end_date,c.total_days,c.total_hours,c.status,c.return_expected_date,c.return_actual_date,c.return_status FROM occupational_leave_cases c JOIN users u ON u.id=c.collaborator_id LEFT JOIN branches b ON b.id=u.branch_id LEFT JOIN sectors s ON s.id=u.sector_id WHERE c.company_id=${cid} ORDER BY c.start_date DESC`);const headers=["Colaborador","Filial","Setor","Tipo","Emissão","Início","Fim","Dias","Horas","Status","Retorno previsto","Retorno efetivo","Status retorno"];const lines=[headers,...rowsOf(r).map((x:any)=>[x.name,x.branch,x.sector,x.document_type,dateOnly(x.issue_date),dateOnly(x.start_date),dateOnly(x.end_date),x.total_days,x.total_hours,x.status,dateOnly(x.return_expected_date),dateOnly(x.return_actual_date),x.return_status])];return{csv:lines.map(row=>row.map(v=>`"${String(v??"").replace(/"/g,'""')}"`).join(";")).join("\n")}}),
});
